server:
  port: 8087

spring:
  application:
    name: INVENTORY-SERVICE


  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5433/inventory_db
    username: inventory
    password: inventory

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      max-poll-records: 500  # Batch size for consuming

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.blinkit.inventory: DEBUG
